M48
; DRILL file {KiCad (6.0.10-0)} date Thursday, February 16, 2023 at 02:34:14 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-16T14:34:14-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10-0)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0598
%
G90
G05
T1
X5.66Y-3.64
X6.02Y-3.92
T2
X5.84Y-3.18
X5.84Y-3.38
T0
M30
